modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="madmincraftrs_parkour_mod"
version="1.1.0"
displayName="MadMincraftr's Parkour Mod"
credits="Mod made with the tool MCreator."
displayURL="https://www.curseforge.com/minecraft/mc-mods/madmincraftrs-parkour-mod"
logoFile="logo.png"
authors="MadMincraftr"
description='''
R1.1.0 | Adds parkour blocks and effects that let you make maps, or share a small parkour build with your friend.
'''

[[dependencies.madmincraftrs_parkour_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




