modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="normal_parkour_mod"
version="1.2.1"
displayName="Normal Parkour"
credits="Mod made with the tool MCreator."
displayURL="https://www.curseforge.com/minecraft/mc-mods/madmincraftrs-parkour-mod"
logoFile="logo.png"
authors="MadMincraftr"
description='''
RELEASE 1.2.1 | Adds parkour blocks and effects that let you make maps, or share a small parkour build with your friend.
'''

[[dependencies.normal_parkour_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




