modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="madmincraftrs_parkour_mod"
version="01"
displayName="MadMincraftr's Parkour Mod"
credits="Mod made with the tool MCreator."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MadMincraftr"
description='''
DEV BUILD 01
'''

[[dependencies.madmincraftrs_parkour_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




