modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="madmincraftrs_parkour_mod"
version="0.5.0"
displayName="MadMincraftr's Parkour Mod"
credits="Mod made with the tool MCreator."
displayURL="https://www.curseforge.com/minecraft/mc-mods/madmincraftrs-parkour-mod"
logoFile="logo.png"
authors="MadMincraftr"
description='''
BETA 1 FOR RELEASE 1.0.0
'''

[[dependencies.madmincraftrs_parkour_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




